name: Build and publish packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build and publish package
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work
        
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
      
    - name: Nerdbank.GitVersioning
      # You may pin to the exact commit or the version.
      # uses: dotnet/nbgv@49d4f35f34d895d282b99855b2e0034f8f608ba5
      uses: dotnet/nbgv@v0.4.0
      with:
        setAllVars: true
      
    - run: echo "NBGV_Version $NBGV_Version"
    
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
          
    - name: Install MAUI Workloads
      run: |
        dotnet workload install android --ignore-failed-sources
        dotnet workload install maui --ignore-failed-sources
        
    - name: Build
      run: dotnet build ./Maui.NeoControls.sln --configuration Release
    - name: Pack
      run: dotnet pack ./Maui.NeoControls.sln --output ./artifacts --configuration Release
        
    - name: Publish NuGet.Org
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: ./Maui.NeoControls.sln
        INCLUDE_SYMBOLS: true
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        VERSION_STATIC: $NBGV_Version
