name: Build and publish packages

on:
  push:
    branches: [ main ]

jobs:
  build:

    name: Build and publish package
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
        
    - name: Fetch all repository
      run: git fetch --unshallow
      
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        
    - name: Change version on csproj file
      run: sed -i -e 's/Version>[0-9a-z.-]*</Version>'$GITVERSION_NUGETVERSION'</' ./Maui.NeoControls/Maui.NeoControls.csproj

    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
          
    - name: Install MAUI Workloads
      run: |
        dotnet workload install android --ignore-failed-sources
        dotnet workload install maui --ignore-failed-sources
        
    - name: Build
      run: dotnet build ./Maui.NeoControls.sln --configuration Release
    - name: Pack
      run: dotnet pack ./Maui.NeoControls.sln  --output ./artifacts --configuration Release

    - name: Push Nupkg to GitHub Packages
      uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
      with:
        nupkg-path:  '**\*\artifacts\*.nupkg'
        repo-owner:  'felipebaltazar'
        gh-user:  'felipebaltazar'
        token:  ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish NuGet.Org
      uses: brandedoutcast/publish-nuget@v2.5.5
      if: github.ref == 'refs/heads/main'
      with:
        PROJECT_FILE_PATH: ./Maui.NeoControls/Maui.NeoControls.csproj
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
